### ISSUE TITLE
Final steps for AliDPG validation

### ISSUE THREAD

**Issue by dberzano** [alisw/release-validation#51]
- [x] Report job type in JIRA issues: #52 
- [x] Automatic recollection of validation reports #53
- [x] Return a failure in case validation reports are non-empty #53
- [x] "Pretend mode" for TPC SP calibration to work around statistics issues #55
- [x] Fix validation report issues #53
- [x] Fix code coverage report
- [x] Clarify `--run --dryrun`: update README.md and generate dummy files #53
- [x] Improve coverage
- [x] Update containers with latest cctools (for Makeflow) alisw/docks#166

**Comment by dberzano** [comment]
Concerning the TPC SP, we've launched a full reconstruction workflow over 300 files from LHC17f with no events limit to see if we have enough stats (we probably do not) and to measure the time it takes.

**Comment by dberzano** [comment]
All blocking issues have been sorted out. We can run safely the reconstruction over 70 files (over 300 files staged), the list is [this one](https://github.com/alisw/release-validation/blob/master/datasets/LHC17f.txt). Results of Grid Space Point Calibration have been imported to the input dataset on EOS for using them as they are during the OCDB creation phase.

**Comment by dberzano** [comment]
@chiarazampolli @fprino @mconcas

**Comment by dberzano** [comment]
(Note that we still need alisw/AliDPG#134 ported to v5-09-XX, and a tag from there.)
